# Generated by Django 6.0.2 on 2026-04-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_patientprofile_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor_certificates/'),
        ),
    ]
