# Generated by Django 6.0.2 on 2026-04-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctorprofile_doctor_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
